services:
  gateway:
    build: gateway
    image: wallet-gateway
    container_name: wallet-gateway
    ports:
      - "9090:9090"
    depends_on:
      - server
    environment:
      - WALLET_SERVER_URL=http://server:8080

  server:
    build: server
    image: wallet-server
    container_name: wallet-server
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/wallet
      - SPRING_DATASOURCE_USERNAME=wallet
      - SPRING_DATASOURCE_PASSWORD=wallet

  db:
    image: postgres:16.1
    container_name: wallet-postgers
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_PASSWORD=wallet
      - POSTGRES_USER=wallet
      - POSTGRES_DB=wallet
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10